### PR TITLE
Removing import statement from module-types extra. Resolves #2027.

### LINKED ISSUE #2027: Module not found: Error: Can't resolve '../system-core'
I am bundling s.js with webpack but webpack can't find the module 'system-core' when I `require` 'systemjs/dist/extras/module-types.js'.  I can see that the module 'system-core' exists in the src folder but it is not present in the dist folder.  Is it possible to add the 'system-core' module to the dist folder and publish it to npm?

### PR DESCRIPTION
**Pull request by joeldenning**
See #2027. Note that the module-types extra has an `import` in it when it shouldn't.

https://github.com/systemjs/systemjs/blob/c08c92dcdb0850b999b6cf4c180702e01ae8b04d/dist/extras/module-types.js#L5

### CODE REVIEW

File: src/extras/module-types.js [hunk 1]
```diff
@@ -2,91 +2,94 @@
...
-    throw Error(msg + ', loading ' + url + (parent ? ' from ' + parent : ''));
-  }
-};
\ No newline at end of file
+    }
+    function loadError (msg) {
+      throw Error(msg + ', loading ' + url + (parent ? ' from ' + parent : ''));
+    }
+  };
+})();
```
Comment (guybedford) [inline src/extras/module-types.js]: There's no need to do an IIFE wrapping in modules as they already have local scope.

Comment (guybedford) [reply src/extras/module-types.js]: Ahh the extras are scripts! Seems I completely forgot that! nvm
