### PR TITLE
Fix named-register.js - omit name from register call. Resolves #2293.

### LINKED ISSUE #2293: registration[1] is not a function
Got a problem because of #2144. `setTimeout` to `promise.resolve().then(...)` means macro task to micro task, but the micro task will run immediately in script. When trying to get register, the `firstNamedDefine` can't be got, because it has been destroyed. So this error 'registration[1] is not a function' occurs. The timeline likes:

execute scripnt -> register named module -> clear `firstNamedDefine` -> script's `load` event triggered -> get register -> 
`firstNamedDefine` is null

It'll be reproduce by running only running the test suit 'Named System.register'.

I wonder if there's necessary to clear the `firstNameDefined` by delay? This process seems OK(maybe):

execute script -> register named module -> update `firstNamedDefine` -> script's `load` event triggered -> get register -> clear `firstNamedDefine` -> execute script -> ...

### PR DESCRIPTION
**Pull request by joeldenning**
See https://github.com/systemjs/systemjs/issues/2327#issuecomment-831756226 and #2293. cc @anhallbe who found the problem.

System core expects to never be called with the string name as the first argument, but named-register does so. The reason the tests pass and named-register works for some people is that named-register overrides `getRegister` to retrieve from `registerRegistry` for named registers. However, when that doesn't happen, the `lastRegister` in system core is just incorrect!

### CODE REVIEW

File: src/extras/named-register.js [hunk 1]
```diff
@@ -35,7 +35,7 @@
         firstNamedDefine = null;
       });
     }
-    return register.apply(this, arguments);
+    return register.apply(deps, declare);
```
Comment (anhallbe) [inline src/extras/named-register.js:38]: This should probably be:
```js
return register.apply(this, [deps, declare]);
```

I don't really understand why the unit tests doesn't pick up on this issue, but here's a repro with the above fix:

https://codesandbox.io/s/broken-sun-c3xjm?file=/index.html

See the `named-register-fixed.js`

**Review by guybedford — COMMENTED** [review]
Thanks for catching this! Is it possible to get a test to cover this case?

**Comment by joeldenning** [comment]
> Is it possible to get a test to cover this case?

Not without some reworking of the tests - currently the amd.js extra is executed before the named-register extra, which alters behavior in such a way that the test would pass both with and without the test.

File: src/extras/named-register.js (hunk 1 above)
Comment (joeldenning) [reply src/extras/named-register.js:38]: Ah good catch, I thought I had tested this but now that I see the problem I wonder why my testing wouldn't have noticed that it wasn't correct.

I've updated it now.

**Review by guybedford — APPROVED** [review]

**Comment by restjohn** [comment]
FYI, this appears to be a breaking change with respect to previous behavior.  After updating to 6.9.0, `System.import()` now returns the last named register module instead of the actual module fetched from the URL.  For example, at initialization, I do 
```
const lib1Exports = ...
const lib2Exports = ...
System.register('lib1', [],  _export => {
  return {
    execute: () => {
      _export(lib1Exports)
      // deliberate undefined return because returning something here screws up systemjs
      return void(0)
    }
  }
})
System.register('lib2', [], _export => {
  return {
    execute: () => {
      _export(lib2Exports)
      return void(0)
    }
  }
})
```
Then later
```
const lib3 = await System.import('/libs/lib3.umd.js')
lib3 === lib2Exports // true
```
The above worked as expected with version 6.8.x and the named-register/amd extras.
