### PR TITLE
Fixing IE11 compatibility for System.entries(). Resolves #1935.

### LINKED ISSUE #1935: Compatibility with IE11
This line here https://github.com/systemjs/systemjs/blob/0ec9da6b46d38da3813357124202b4c43da729d6/dist/system.js#L788 breaks compatibility with IE11.
I think Symbol.iterator is[ not supported at all in IE11](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol/iterator#Browser_compatibility).

### PR DESCRIPTION
**Pull request by joeldenning**
Computed object properties are not supported in IE11. See #1935

### CODE REVIEW

File: src/features/registry.js [hunk 1]
```diff
@@ -75,7 +75,12 @@ systemJSPrototype.entries = function () {
         done: key === undefined,
         value: key !== undefined && [key, ns]
       };
-    },
-    [iterator]: function() { return this }
+    }
   };
+
+  if (iterator) {
```
Comment (guybedford) [inline src/features/registry.js]: I don't mind if we remove the guard. Setting the 'undefined' string in older environments isn't going to cause any issues. And yes, I do care about the bytes that much!

Comment (joeldenning) [reply src/features/registry.js]: 👍 updated

**Comment by guybedford** [comment]
Thanks so much. Released in 3.1.4.
